[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables will be set in Netlify dashboard
# REACT_APP_API_URL = "https://your-backend-url.com" 